# Generated by Django 3.1 on 2020-08-17 01:27

from django.db import migrations, models
import django.db.models.deletion
import djangoerp.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('template_name', models.CharField(blank=True, max_length=255, verbose_name='template name')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='icon')),
                ('template_name', models.CharField(blank=True, max_length=255, verbose_name='template name')),
                ('context', models.TextField(blank=True, help_text='Use the JSON syntax.', null=True, validators=[djangoerp.core.models.validate_json], verbose_name='context')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('new_window', models.BooleanField(default=False, verbose_name='New window')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('only_authenticated', models.BooleanField(default=True, verbose_name='Only for authenticated users')),
                ('only_staff', models.BooleanField(default=False, verbose_name='Only for staff users')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='menus.menu', verbose_name='menu')),
                ('only_with_perms', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='Only with following permissions')),
                ('submenu', models.ForeignKey(blank=True, db_column='submenu_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='menus.menu', verbose_name='sub-menu')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ('menu', 'sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
            ],
            options={
                'verbose_name': 'bookmark',
                'verbose_name_plural': 'bookmarks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('menus.link',),
        ),
    ]
