# Generated by Django 3.1 on 2020-08-17 01:27

from django.db import migrations, models
import django.db.models.deletion
import djangoerp.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'signature',
                'verbose_name_plural': 'signatures',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.PositiveIntegerField()),
                ('send_email', models.BooleanField(default=True, verbose_name='send email')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.signature')),
                ('subscriber_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_id', models.PositiveIntegerField()),
                ('follower_id', models.PositiveIntegerField()),
                ('followed_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('follower_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'follow relation',
                'verbose_name_plural': 'follow relations',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('signature', models.CharField(max_length=50, verbose_name='signature')),
                ('template', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='template')),
                ('context', models.TextField(blank=True, help_text='Use the JSON syntax.', null=True, validators=[djangoerp.core.models.validate_json], verbose_name='context')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('backlink', models.CharField(blank=True, max_length=200, null=True, verbose_name='backlink')),
                ('source_id', models.PositiveIntegerField()),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('target_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('read', models.DateTimeField(blank=True, null=True, verbose_name='read on')),
                ('dispatch_uid', models.CharField(max_length=32, verbose_name='dispatch UID')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.signature', verbose_name='signature')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created', 'id'),
                'get_latest_by': '-created',
                'unique_together': {('target_content_type', 'target_id', 'dispatch_uid')},
                'index_together': {('target_content_type', 'target_id', 'dispatch_uid')},
            },
        ),
    ]
